<a href="https://colab.research.google.com/github/Muskan-Kandel/aes/blob/muskan%2Fdata-preprocessing/AES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
asap_raw = pd.read_csv('/content/drive/MyDrive/aes/training_set_rel3.csv', encoding='latin1')
asap_raw.shape

(12978, 28)

In [4]:
asap_raw.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,rater3_domain1,domain1_score,rater1_domain2,rater2_domain2,domain2_score,...,rater2_trait3,rater2_trait4,rater2_trait5,rater2_trait6,rater3_trait1,rater3_trait2,rater3_trait3,rater3_trait4,rater3_trait5,rater3_trait6
0,1,1,"Dear local newspaper, I think effects computer...",4.0,4.0,NaN,8.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",5.0,4.0,NaN,9.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",4.0,3.0,NaN,7.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",5.0,5.0,NaN,10.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,"Dear @LOCATION1, I know having computers has a...",4.0,4.0,NaN,8.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
prompt3 = pd.read_csv('/content/drive/MyDrive/aes/Prompt-3.csv', encoding='latin1')
prompt3.head()

   Essay ID  Content  Prompt Adherence  Language  Narrativity
0      5978        0                 0         1            1
1      5979        3                 3         2            2
2      5980        2                 2         2            1
3      5981        0                 1         0            0
4      5982        1                 1         1            1

In [6]:
prompt4 = pd.read_csv('/content/drive/MyDrive/aes/Prompt-4.csv', encoding='latin1')
prompt4.head()

   Essay ID  Content  Prompt Adherence  Language  Narrativity
0      8863        0                 0         0            0
1      8864        0                 0         0            0
2      8865        3                 3         3            3
3      8866        3                 3         2            2
4      8867        2                 2         2            2

In [7]:
prompt5 = pd.read_csv('/content/drive/MyDrive/aes/Prompt-5.csv', encoding='latin1')
prompt5.head()

   Essay ID  Content  Prompt Adherence  Language  Narrativity
0     11827        2                 2         2            2
1     11828        3                 3         3            3
2     11829        2                 2         2            2
3     11830        1                 0         1            1
4     11831        4                 4         4            4

In [8]:
prompt6 = pd.read_csv('/content/drive/MyDrive/aes/Prompt-6.csv', encoding='latin1')
prompt6.head()

   Essay ID  Content  Prompt Adherence  Language  Narrativity
0     15491        4                 3         2            2
1     15972        1                 1         3            2
2     16109        4                 4         3            3
3     16228        2                 1         4            3
4     16352        3                 3         4            4

In [17]:
filtered= asap_raw[asap_raw['essay_set'].isin([3,4,5,6])]
print("Total rows in prompt 3-6 is", len(filtered))
print("Columns : ", list(filtered.columns))
print("Per prompt : ", filtered['essay_set'].value_counts().sort_index().to_dict())
for i in [3,4,5,6]:
  p = pd.read_csv(f'/content/drive/MyDrive/aes/Prompt-{i}.csv')
  print(f'prompt-{i}.csv rows: {len(p)}, columns: {list(p.columns)}')

  #check for essay_id overlap in asap dataset and prompt 3-6 datasets

  overlap = filtered[filtered['essay_set'] == i]['essay_id'].isin(p['Essay ID']).sum()
  print(f'Matching essay_ids: {overlap}/{len(p)}')

Total rows in prompt 3-6 is 7103
Columns :  ['essay_id', 'essay_set', 'essay', 'rater1_domain1', 'rater2_domain1', 'rater3_domain1', 'domain1_score', 'rater1_domain2', 'rater2_domain2', 'domain2_score', 'rater1_trait1', 'rater1_trait2', 'rater1_trait3', 'rater1_trait4', 'rater1_trait5', 'rater1_trait6', 'rater2_trait1', 'rater2_trait2', 'rater2_trait3', 'rater2_trait4', 'rater2_trait5', 'rater2_trait6', 'rater3_trait1', 'rater3_trait2', 'rater3_trait3', 'rater3_trait4', 'rater3_trait5', 'rater3_trait6']
Per prompt :  {3: 1726, 4: 1772, 5: 1805, 6: 1800}
prompt-3.csv rows: 1726, columns: ['Essay ID', 'Content', 'Prompt Adherence', 'Language', 'Narrativity']
Matching essay_ids: 1726/1726
prompt-4.csv rows: 1772, columns: ['Essay ID', 'Content', 'Prompt Adherence', 'Language', 'Narrativity']
Matching essay_ids: 1772/1772
prompt-5.csv rows: 1805, columns: ['Essay ID', 'Content', 'Prompt Adherence', 'Language', 'Narrativity']
Matching essay_ids: 1805/1805
prompt-6.csv rows: 1800, columns: ['Essay ID', 'Content', 'Prompt Adherence', 'Language', 'Narrativity']
Matching essay_ids: 1800/1800

This shows for every essay in filtered asap_raw data (Sets 3, 4, 5, and 6), there is a corresponding row in the Prompt-X.csv files.